In [1]:
from qiskit.circuit.random import random_circuit 
from qiskit.primitives import Sampler 
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector, Operator 
import numpy as np
import matplotlib.pyplot as plt 
from qiskit.circuit.library.n_local.real_amplitudes import RealAmplitudes
from qiskit.circuit.library.n_local.efficient_su2 import EfficientSU2

from vqls_prototype.tomography import FullQST, RealQST, SimulatorQST, ShadowQST

In [2]:
nqbits = 3
circ = RealAmplitudes(nqbits, entanglement='full', reps=3, insert_barriers=False)
parameters = 4*np.pi*np.random.rand(circ.num_parameters)

In [3]:
amp = Statevector(circ.bind_parameters(parameters)).data.real
amp

array([-0.16600388, -0.04701527, -0.3374492 , -0.04725767,  0.24768462,
       -0.59129611,  0.62534368,  0.22824011])

In [4]:
sim_qst = SimulatorQST(circ)
ref = sim_qst.get_relative_amplitude_sign(parameters)
ref

array([-1., -1., -1., -1.,  1., -1.,  1.,  1.])

In [5]:
sampler = Sampler()
real_qst = RealQST(circ, sampler)
sol = real_qst.get_relative_amplitude_sign(parameters)
sol

array([ 1.,  1.,  1.,  1., -1.,  1., -1., -1.])

In [6]:
assert np.allclose(ref, sol) or np.allclose(ref, -sol)

In [7]:
from qiskit import Aer 
backend = Aer.get_backend('statevector_simulator')
full_qst = FullQST(circ, backend)
sol = full_qst.get_relative_amplitude_sign(parameters)
sol

array([ 1., -1.,  1.,  1., -1., -1.,  1., -1.])

In [8]:
# assert np.allclose(ref, sol) or np.allclose(ref, -sol)

AssertionError: 

In [9]:
shadow_qst = ShadowQST(circ, sampler, 1000) 
shadow_qst.get_relative_amplitude_sign(parameters)

array([ 1.,  1.,  1.,  1., -1.,  1., -1., -1.])