In [1]:
import numpy as np
from qiskit.opflow import (
    Z,
    X,
    Y,
    I,
    Plus,
    Minus,
    Zero, One,
    CX, S, H, T, CZ, Swap,
    TensoredOp
)
from qiskit.quantum_info.operators import Operator, Pauli
zero_op = (I + Z) / 2
one_op = (I - Z) / 2

In [7]:
Operator(X).input_dims()[0]

2

# N = 2

In [98]:
Operator(zero_op^one_op).data.real + Operator(one_op^zero_op).data.real

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [99]:
Operator(zero_op^zero_op).data.real + Operator(one_op^one_op).data.real

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [101]:
0.5*(Operator(X^X).data.real - Operator(Y^Y).data.real)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [169]:
0.5*(Operator(X^X).data.real + Operator(Y^Y).data.real)

array([[0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
- Operator(Y^Y).data.real

array([[-0., -0., -0.,  1.],
       [-0., -0., -1., -0.],
       [-0., -1., -0., -0.],
       [ 1., -0., -0., -0.]])

In [104]:
Operator(I^X).data.real

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [106]:
Operator(X^I).data.real

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

# N = 3 

In [73]:
Operator(TensoredOp([zero_op]*3)).data.real + Operator(TensoredOp([one_op]*3)).data.real

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [74]:
Operator(zero_op^TensoredOp(2*[one_op])).data.real + Operator(one_op^TensoredOp(2*[zero_op])).data.real

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
Operator(zero_op^one_op^zero_op).data.real + Operator(one_op^zero_op^one_op).data.real

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
Operator(zero_op^zero_op^one_op).data.real + Operator(one_op^one_op^zero_op).data.real

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [122]:
-768*(Operator(zero_op^zero_op^X).data.real + Operator(one_op^one_op^X).data.real)

array([[  -0., -768.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [-768.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -768.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0., -768.,   -0.]])

In [121]:
-512*(Operator(zero_op^one_op^X).data.real + Operator(one_op^zero_op^X).data.real)

array([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0., -512.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0., -512.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0., -512.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0., -512.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.]])

In [155]:
-576*(Operator(zero_op^X^zero_op).data.real + Operator(one_op^X^one_op).data.real)

array([[  -0.,   -0., -576.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [-576.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -576.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0., -576.,   -0.,   -0.]])

In [175]:
-640 * ( 0.5 * Operator(I ^ ((X^X) + (Y^Y))).data.real )

array([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0., -640.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0., -640.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0., -640.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0., -640.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.]])

In [187]:
-448 * (Operator(zero_op^X^one_op).data.real + Operator(one_op^X^zero_op).data.real)

array([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0., -448.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0., -448.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0., -448.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0., -448.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.]])

In [188]:
-384*( 0.5*(Operator( I^((X^X) - (Y^Y))).data.real) )

array([[  -0.,   -0.,   -0., -384.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [-384.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -384.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
       [  -0.,   -0.,   -0.,   -0., -384.,   -0.,   -0.,   -0.]])

In [238]:
sp = Operator(np.array([[0,1],[0,0]]))
sm = Operator(np.array([[0,0],[1,0]]))

Operator(sp^sm^sp)

Operator([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]],
         input_dims=(2, 2, 2), output_dims=(2, 2, 2))

In [229]:
Operator(np.array([[0,1],[-1,0]])).data.real

array([[ 0.,  1.],
       [-1.,  0.]])

In [228]:
Operator(X-Y)

Operator([[0.+0.j, 1.+1.j],
          [1.-1.j, 0.+0.j]],
         input_dims=(2,), output_dims=(2,))